anuncios_anuncios:
    resource: "@AnunciosBundle/Resources/config/routing/anuncios.yml"
    prefix:   /anuncios

anuncios_homepage:
    path:     /
    defaults: { _controller: AnunciosBundle:Default:index }
